### ISSUE TITLE
Undefined control sequence with \pgfuseshading inside pgfpicture

### ISSUE THREAD

**Issue by dcpurton** [michal-h21/dvisvgm4ht#3]
`\pgfuseshading` generates an undefined control sequence when used inside a `pgfpicture` environment:

```TeX
! Undefined control sequence.
\b:tikzpicture ...fined \EndPicture \end@pict@cmd 
                                                  \fi 
l.8 ...oint{1cm}{0cm}] {\pgfuseshading{myshadingD}
                                                  }
? 
```

# MWE

This example is taken from the `pgf` manual.

```TeX
\documentclass{article}
\def\pgfsysdriver{pgfsys-dvisvgm4ht.def}
\usepackage{pgf}
\begin{document}
\begin{pgfpicture}
  \pgfdeclareverticalshading{myshadingD}
  {20pt}{color(0pt)=(red); color(20pt)=(blue)}
  \pgftext[at=\pgfpoint{1cm}{0cm}] {\pgfuseshading{myshadingD}}
  \pgftext[at=\pgfpoint{2cm}{0.5cm}]{\pgfuseshading{myshadingD}}
\end{pgfpicture}
\end{document}
```

**Comment by dcpurton** [comment]
Sorry! Should have mentioned that this occurs with the development version of `pgf`, not with the version 3.1.1 which I currently have installed.

It seems to happen in other situations too.

**Comment by michal-h21** [comment]
No, there is an error. There was missing parameter for the `\Picture` command, so it ate an `\fi` command. It should be fixed now.

**Comment by dcpurton** [comment]
Thanks, this is fixed in my tests.

**Comment by Iey4iej3** [comment]
Since it is said fixed, let us close this issue.

**Comment by michal-h21** [comment]
@Iey4iej3 you are right, thanks for reminding me.
